language: java
jdk: openjdk11
dist: xenial
os: linux
env:
  global:
    JAVA_OPTS=-Xmx2g
script:
  - bash gradlew buildPlugin
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/